project_id_env: INATRN_CROWDIN_PROJECT_ID
api_token_env: INATRN_CROWDIN_PERSON_TOKEN
preserve_hierarchy: true

files:
  - source: /src/i18n/strings.ftl
    dest: /ReactNative/strings.ftl
    translation: /src/i18n/l10n/%two_letters_code%.ftl
    type: ftl
    languages_mapping:
      two_letters_code:
        bg-FR: bg
        en-AU: en-AU
        en-GB: en-GB
        en-NZ: en-NZ
        en-US: en
        es-AR: es-AR
        es-CO: es-CO
        es-CR: es-CR
        es-ES: es
        es-MX: es-MX
        fr-CA: fr-CA
        fr-FR: fr
        gu-IN: gu
        ml-IN: ml
        pa-IN: pa
        pt-BR: pt-BR
        pt-PT: pt
        si-LK: si
        sr-CS: sr
        sv-SE: sv
        zh-CN: zh-CN
        zh-HK: zh-HK
        zh-TW: zh-TW
