project_id_env: INATRN_CROWDIN_PROJECT_ID
api_token_env: INATRN_CROWDIN_PERSON_TOKEN
preserve_hierarchy: true

files:
  - source: /src/i18n/strings.ftl
    dest: /ReactNative/strings.ftl
    # Note: this uses the Crowdin locale which always has a region. We need to
    # mess with this later in i18ncli
    translation: /src/i18n/l10n/%locale%.ftl
    type: ftl
