name: Crowdin Action

on:
  push:
    branches: [ 2103-post-to-crowdin ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          # Debug
          command_args: '--verbose'
          upload_sources_args: '--verbose'
          download_sources_args: '--verbose'
          # Note: a lot of the way this behaves is controlled in crowdin.yml,
          # e.g. the path to the source files and paths to translations
          # Upload options
          upload_sources: true
          upload_translations: false
          # Download options
          download_translations: true
          skip_untranslated_strings: true
          skip_untranslated_files: true
          export_only_approved: true
          # Pull request options
          localization_branch_name: l10n_2103_post_to_crowdin
          create_pull_request: true
          pull_request_title: 'New Crowdin Translations'
          pull_request_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: '2103-post-to-crowdin'
        env:
          # A classic GitHub Personal Access Token with the 'repo' scope selected (the user should have write access to the repository).
          GITHUB_TOKEN: ${{ secrets.CROWDIN_GITHUB_TOKEN }}
          
          # A numeric ID, found at https://crowdin.com/project/<projectName>/tools/api
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}

          # Visit https://crowdin.com/settings#api-key to create this token
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
